const $ = (s) => document.querySelector(s);
const store = {
  get(k, fallback) { try { return JSON.parse(localStorage.getItem(`athleteos:${k}`)) ?? fallback; } catch { return fallback; } },
  set(k, v) { localStorage.setItem(`athleteos:${k}`, JSON.stringify(v)); }
};

const state = {
  page: 'dashboard',
  events: store.get('events', [{ name: 'National Taekwondo Championship', date: '2026-08-14', venue: 'Indira Gandhi Indoor Stadium, New Delhi', status: 'Registration opens Jul 20', verified: true }]),
  calendar: store.get('calendar', [{ title: 'Strength & conditioning', date: '2026-07-14', type: 'Training' }, { title: 'Weigh-in reminder', date: '2026-08-13', type: 'Competition' }]),
  medals: store.get('medals', [{ event: 'Delhi State Open', medal: 'Gold', category: 'Junior -58 kg', date: '2026-03-08' }, { event: 'Inter-school Championship', medal: 'Silver', category: 'Junior -58 kg', date: '2025-11-21' }]),
  docs: store.get('docs', [{ name: 'Medical Fitness Certificate.pdf', tag: 'Medical', expiry: '2027-01-15' }, { name: 'School ID Card.jpg', tag: 'Identity', expiry: '2026-12-31' }]),
  weight: store.get('weight', [58.6, 58.4, 58.2, 58.1, 57.9, 57.8, 57.8]),
  checklist: store.get('checklist', [{ item: 'Dobok and belt', done: true }, { item: 'Guards and gloves', done: true }, { item: 'Mouth guard', done: false }, { item: 'ID card and registration', done: false }, { item: 'Water bottle', done: true }])
};

const nav = [
  ['dashboard', '⌂', 'Dashboard'], ['events', '◉', 'AI Event Watch'], ['calendar', '□', 'Calendar'], ['medals', '★', 'Medal Cabinet'], ['vault', '▣', 'Document Vault'], ['profile', '◌', 'Athlete Profile'], ['weight', '↗', 'Weight Tracker'], ['checklist', '✓', 'Checklist']
];
const titles = { dashboard: ['COMMAND CENTER', 'Good evening, Arjun.'], events: ['EVENT INTELLIGENCE', 'AI Event Watch'], calendar: ['SCHEDULE', 'Your training calendar'], medals: ['ACHIEVEMENTS', 'Medal cabinet'], vault: ['SECURE STORAGE', 'Document vault'], profile: ['ATHLETE', 'Profile & competition class'], weight: ['PERFORMANCE', 'Weight tracker'], checklist: ['COMPETITION READY', 'Tournament checklist'] };

function persist() { ['events','calendar','medals','docs','weight','checklist'].forEach(k => store.set(k, state[k])); }
function toast(message) { const t = $('#toast'); t.textContent = message; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 2600); }
function daysTo(date) { return Math.max(0, Math.ceil((new Date(date) - new Date()) / 86400000)); }
function card(label, value, note, icon = '◌') { return `<article class="metric card"><div class="metric-icon">${icon}</div><div><p>${label}</p><strong>${value}</strong><small>${note}</small></div></article>`; }
function button(text, action, kind = '') { return `<button class="btn ${kind}" data-action="${action}">${text}</button>`; }
function empty(text) { return `<div class="empty">${text}</div>`; }

function dashboard() {
  const next = state.events[0]; const readiness = Math.round((state.checklist.filter(x=>x.done).length/state.checklist.length)*35 + 54);
  return `<div class="hero card"><div><span class="pill">NEXT COMPETITION</span><h2>${next.name}</h2><p>${next.venue}</p><div class="hero-meta"><b>${daysTo(next.date)} days</b><span>•</span><span>${new Date(next.date).toLocaleDateString('en-IN', { day:'numeric', month:'long', year:'numeric' })}</span></div>${button('View event details', 'events', 'primary')}</div><div class="countdown"><span>COUNTDOWN</span><strong>${daysTo(next.date)}</strong><small>DAYS TO GO</small></div></div>
  <div class="metrics">${card('Readiness score', readiness + '%', 'Up 6% this week', '↗')}${card('Current weight', state.weight.at(-1)+' kg', 'Target: -58 kg', '⚖')}${card('Training progress', '4 / 5', 'Sessions this week', '◒')}${card('Unread updates', '2', 'Verified official sources', '◉')}</div>
  <div class="grid two"><article class="card panel"><div class="panel-head"><div><p class="eyebrow">EVENT WATCH</p><h3>Latest verified update</h3></div><span class="verified">● Verified</span></div><div class="update"><span class="update-icon">↻</span><div><b>Registration timeline published</b><p>National Taekwondo Championship registration opens July 20. Review the circular and prepare documents.</p><small>Official federation update · 2h ago</small></div></div>${button('Open AI Event Watch', 'events')}</article><article class="card panel"><div class="panel-head"><div><p class="eyebrow">TODAY</p><h3>Training focus</h3></div><span class="tag">6:00 PM</span></div><div class="training"><span>🥋</span><div><b>Sparring & reaction drills</b><p>90 minutes · Coach Mehta</p></div></div><div class="progress"><i style="width:80%"></i></div><small>4 of 5 training sessions completed</small></article></div>`;
}
function events() { return `<div class="page-actions">${button('+ Track tournament', 'add-event', 'primary')}${button('↻ Manual scan', 'scan')}</div><div class="scan card"><div class="scanner">◉</div><div><span class="pill">AI EVENT WATCH</span><h2>Official updates, without the noise.</h2><p>Track tournament sites, circulars, registration portals and official social accounts. Notifications appear only when verified information changes.</p></div><div class="scan-controls"><label>Background scan<select id="scan-frequency"><option>Every 24 hours</option><option>Every 12 hours</option><option>Every 6 hours</option><option>Every hour</option></select></label></div></div><div class="list">${state.events.map((e,i)=>`<article class="card event"><div class="event-date"><b>${new Date(e.date).toLocaleDateString('en',{month:'short'}).toUpperCase()}</b><strong>${new Date(e.date).getDate()}</strong></div><div class="event-main"><div class="panel-head"><h3>${e.name}</h3><span class="verified">● ${e.verified?'Verified':'Watching'}</span></div><p>⌖ ${e.venue}</p><small>${e.status}</small></div><div class="event-actions">${button('Details', `event-${i}`)}<button class="plain" data-action="remove-event-${i}">Remove</button></div></article>`).join('')}</div>`; }
function calendar() { return `<div class="page-actions">${button('+ Add schedule item', 'add-calendar', 'primary')}</div><div class="card calendar-card"><div class="month"><button data-action="prev-month">‹</button><h2>July 2026</h2><button data-action="next-month">›</button></div><div class="weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span>${x}</span>`).join('')}</div><div class="days">${Array.from({length:31},(_,i)=>`<div class="day ${i===12?'today':''}"><b>${i+1}</b>${[3,13,19].includes(i)?'<i></i>':''}</div>`).join('')}</div></div><div class="card panel schedule"><div class="panel-head"><h3>Upcoming</h3><span>${state.calendar.length} scheduled</span></div>${state.calendar.map((x,i)=>`<div class="schedule-row"><span class="type ${x.type.toLowerCase()}">${x.type}</span><div><b>${x.title}</b><p>${new Date(x.date).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</p></div><button class="plain" data-action="remove-calendar-${i}">×</button></div>`).join('')}</div>`; }
function medals() { return `<div class="page-actions">${button('+ Add achievement', 'add-medal', 'primary')}</div><div class="metrics">${card('Gold medals', state.medals.filter(x=>x.medal==='Gold').length, 'Career total', '★')}${card('Podium finishes', state.medals.length, 'All tournaments', '♛')}${card('Latest result', state.medals[0]?.medal || '-', state.medals[0]?.event || 'No result', '✦')}</div><div class="medal-grid">${state.medals.map((m,i)=>`<article class="card medal ${m.medal.toLowerCase()}"><div class="medal-icon">★</div><span>${m.medal.toUpperCase()}</span><h3>${m.event}</h3><p>${m.category}</p><small>${m.date}</small><button class="plain" data-action="remove-medal-${i}">Remove</button></article>`).join('')}</div>`; }
function vault() { return `<div class="page-actions">${button('+ Add document', 'add-doc', 'primary')}</div><div class="vault-intro card"><span>▣</span><div><h2>Your competition documents, organized.</h2><p>Stored locally on this device. Add document metadata and keep expiry dates visible.</p></div></div><div class="document-list">${state.docs.map((d,i)=>`<article class="card document"><span class="doc-icon">PDF</span><div><h3>${d.name}</h3><p><span class="tag">${d.tag}</span> Expires ${new Date(d.expiry).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</p></div><button class="plain" data-action="remove-doc-${i}">Remove</button></article>`).join('')}</div>`; }
function profile() { return `<div class="profile-layout"><article class="card athlete-card"><div class="avatar">AK</div><h2>Arjun Kumar</h2><p>Junior Taekwondo athlete</p><div class="belt">BLUE BELT <span></span></div><hr><dl><div><dt>Coach</dt><dd>R. Mehta</dd></div><div><dt>School</dt><dd>Delhi Public School</dd></div><div><dt>Age category</dt><dd>Junior</dd></div><div><dt>Weight category</dt><dd>-58 kg</dd></div></dl></article><article class="card panel"><div class="panel-head"><h3>Competition profile</h3>${button('Edit profile','edit-profile')}</div><div class="profile-copy"><h4>Competition objective</h4><p>Build consistency for the National Taekwondo Championship and make the junior state squad selection list.</p><h4>Achievements</h4><p>Delhi State Open gold medallist. Inter-school silver medallist. 4 tournaments completed.</p></div></article></div>`; }
function weight() { const last=state.weight.at(-1), max=Math.max(...state.weight), min=Math.min(...state.weight); return `<div class="page-actions">${button('+ Log weight', 'add-weight', 'primary')}</div><div class="metrics">${card('Current weight', last+' kg', 'Last logged today', '⚖')}${card('Target class', '-58 kg', (last-58).toFixed(1)+' kg to target', '◎')}${card('7-day change', (last-state.weight[0]).toFixed(1)+' kg', 'Healthy trend', '↘')}</div><article class="card chart"><div class="panel-head"><div><p class="eyebrow">WEIGHT HISTORY</p><h3>Last 7 entries</h3></div><span class="tag">Goal: 58.0 kg</span></div><div class="bars">${state.weight.map((w,i)=>`<div><i style="height:${((w-min+0.15)/(max-min+0.15))*85+10}%"></i><span>${w}</span><small>D${i+1}</small></div>`).join('')}</div></article>`; }
function checklist() { const done=state.checklist.filter(x=>x.done).length; return `<div class="check-hero card"><div><span class="pill">COMPETITION PREP</span><h2>${done} of ${state.checklist.length} items ready</h2><p>Complete your kit before travel day.</p></div><div class="ring"><b>${Math.round(done/state.checklist.length*100)}%</b></div></div><div class="check-list card">${state.checklist.map((x,i)=>`<label class="check-row"><input type="checkbox" data-check="${i}" ${x.done?'checked':''}/><span></span><b>${x.item}</b><small>${x.done?'Ready':'To pack'}</small></label>`).join('')}</div>`; }
const renderers={dashboard,events,calendar,medals,vault,profile,weight,checklist};
function render() { $('#nav').innerHTML=nav.map(([id,icon,label])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span>${icon}</span>${label}</button>`).join(''); const [k,t]=titles[state.page]; $('#section-kicker').textContent=k; $('#page-title').textContent=t; $('#content').innerHTML=renderers[state.page](); }
function form(title, fields, onSubmit) { $('#modal-body').innerHTML=`<p class="eyebrow">ATHLETEOS</p><h2>${title}</h2>${fields.map(f=>`<label>${f.label}<input required name="${f.name}" type="${f.type||'text'}" value="${f.value||''}" placeholder="${f.placeholder||''}"></label>`).join('')}<button class="btn primary" value="default">Save</button>`; const modal=$('#modal'); $('#modal-form').onsubmit=e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.currentTarget)); onSubmit(data); modal.close(); persist(); render(); toast('Saved locally');}; modal.showModal(); }
function action(a) { if (titles[a]) { state.page=a; return render(); } if(a==='scan'){toast('Scan complete: 1 verified update found.'); return;} if(a==='add-event') return form('Track a tournament',[{label:'Tournament name',name:'name'},{label:'Date',name:'date',type:'date'},{label:'Venue',name:'venue'}],d=>state.events.push({...d,status:'Watching official sources',verified:false})); if(a==='add-calendar')return form('Add schedule item',[{label:'Title',name:'title'},{label:'Date',name:'date',type:'date'},{label:'Type',name:'type',placeholder:'Training, School, Travel'}],d=>state.calendar.push(d)); if(a==='add-medal')return form('Add achievement',[{label:'Event',name:'event'},{label:'Medal',name:'medal',placeholder:'Gold, Silver or Bronze'},{label:'Category',name:'category'},{label:'Date',name:'date',type:'date'}],d=>state.medals.unshift(d)); if(a==='add-doc')return form('Add document',[{label:'Document name',name:'name'},{label:'Type',name:'tag',placeholder:'Medical, Identity, Registration'},{label:'Expiry date',name:'expiry',type:'date'}],d=>state.docs.push(d)); if(a==='add-weight')return form('Log current weight',[{label:'Weight (kg)',name:'value',type:'number',value:state.weight.at(-1)}],d=>state.weight.push(Number(d.value))); if(a==='edit-profile') return toast('Profile editing can be connected to your account when cloud sync is enabled.'); const m=a.match(/^remove-(event|calendar|medal|doc)-(\d+)$/); if(m){state[{event:'events',calendar:'calendar',medal:'medals',doc:'docs'}[m[1]]].splice(Number(m[2]),1);persist();render();toast('Removed');} }
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]'); if(p){state.page=p.dataset.page;render();} const a=e.target.closest('[data-action]'); if(a)action(a.dataset.action);}); document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){state.checklist[Number(e.target.dataset.check)].done=e.target.checked;persist();render();} }); $('#notify').onclick=()=>toast('2 verified updates: registration timeline and weather watch.'); render();
